// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFvzXniwijMEWiS0i9pPAS1pF6BT9d2k',
    appId: '1:969238736082:android:2900c2e926639ab29ed10b',
    messagingSenderId: '969238736082',
    projectId: 'mon-cv-f4a25',
    storageBucket: 'mon-cv-f4a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TOR47xKWfeFBZGo1XKaFOwJr368XN4E',
    appId: '1:969238736082:ios:dac3f5279b21fa449ed10b',
    messagingSenderId: '969238736082',
    projectId: 'mon-cv-f4a25',
    storageBucket: 'mon-cv-f4a25.firebasestorage.app',
    iosBundleId: 'com.example.monCv',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPiX1OjBijS3FobPgog7kS3G2-jaGm6I',
    appId: '1:969238736082:web:c4ad72301ff7d44b9ed10b',
    messagingSenderId: '969238736082',
    projectId: 'mon-cv-f4a25',
    authDomain: 'mon-cv-f4a25.firebaseapp.com',
    storageBucket: 'mon-cv-f4a25.firebasestorage.app',
    measurementId: 'G-4P1DXDYSC5',
  );

}